name: Generate Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: AbeloByte
          template: classic
          base: header, activity, community
          config_timezone: Africa/Addis_Ababa
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
